# Generated by Django 3.1.3 on 2020-11-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('phy', models.IntegerField()),
                ('chem', models.IntegerField()),
                ('mathORbio', models.IntegerField()),
                ('gcetphy', models.IntegerField()),
                ('gcetchem', models.IntegerField()),
                ('gcetmath', models.IntegerField()),
                ('rankpm', models.IntegerField()),
                ('neetphy', models.IntegerField()),
                ('neetchem', models.IntegerField()),
                ('neetbio', models.IntegerField()),
                ('neetrank', models.IntegerField()),
                ('File', models.FileField(upload_to='student_files')),
            ],
        ),
    ]
