# Generated by Django 3.1.3 on 2020-11-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UGapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
