# Generated by Django 3.1.3 on 2020-11-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(help_text='info about course', max_length=50)),
                ('course_type', models.CharField(blank=True, choices=[('e', 'Engineering'), ('m', 'Medical')], default='e', max_length=1)),
                ('course_name', models.CharField(blank=True, choices=[('comp', 'Computer Engineering'), ('it', 'Information Technology'), ('mech', 'Mechanical Engineering'), ('etc', 'Electronic and Telecomunication')], default='e', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='userCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.ManyToManyField(to='college.Courses')),
            ],
        ),
    ]
