# Generated by Django 3.1.3 on 2020-11-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20201120_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(blank=True, choices=[('comp', 'Computer Engineering'), ('it', 'Information Technology'), ('mech', 'Mechanical Engineering'), ('etc', 'Electronic and Telecomunication'), ('mbbs', 'MBBS'), ('den', 'Bachelor Dental Science')], default='', max_length=5),
        ),
    ]
