# Generated by Django 3.1.3 on 2020-11-20 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0004_usercollege_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollege',
            name='user',
            field=models.OneToOneField(default='sajal', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
