# Generated by Django 3.1.3 on 2020-11-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='File',
            new_name='FILE',
        ),
    ]
