# Generated by Django 3.1.3 on 2020-11-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20201120_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='chosen_college',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='chosen_course',
            field=models.CharField(default='Not Chosen', max_length=20),
            preserve_default=False,
        ),
    ]
